#!/bin/bash

[ -n "$graphicsArray" ] &&
    commandFailure="Graphics driver installation has failed."

for i in "${graphicsArray[@]}"
do
    case $i in
        amd)
            install mesa-dri vulkan-loader mesa-vulkan-radeon mesa-vaapi mesa-vdpau
        ;;

        amd-32bit)
            install void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit
        ;;

        nvidia)
            install void-repo-nonfree
            xmirror -s "$repository" -r /mnt || die
            install nvidia

            # Enable mode setting for wayland compositors
            # This default should change to drm enabled with more recent nvidia drivers, expect this to be removed in the future.
            case "$bootloader" in
                grub)
                    sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 nvidia_drm.modeset=1/g' /mnt/etc/default/grub || die
                ;;
                uki)
                    sed -i -e 's/loglevel=4/loglevel=4 nvidia_drm.modeset=1/g' /mnt/etc/kernel.d/post-install/60-ukify || die
                ;;
            esac

        ;;

        nvidia-32bit)
            install void-repo-multilib-nonfree void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install nvidia-libs-32bit
        ;;

        intel)
            install mesa-dri vulkan-loader mesa-vulkan-intel intel-video-accel
        ;;

        intel-32bit)
            install void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit
        ;;

        nvidia-nouveau)
            install mesa-dri mesa-nouveau-dri
        ;;

        nvidia-nouveau-32bit)
            install void-repo-multilib
            xmirror -s "$repository" -r /mnt || die
            install libgcc-32bit libstdc++-32bit libdrm-32bit libglvnd-32bit mesa-dri-32bit mesa-nouveau-dri-32bit
        ;;

        *)
            echo "Continuing without graphics drivers..."
        ;;

    esac
done

[ -n "$network" ] && [ "$network" != "none" ] &&
    commandFailure="DHCP client setup has failed."

case "$network" in
    NetworkManager)
        install NetworkManager
        system "ln -s /etc/sv/NetworkManager /var/service"
    ;;
    dhcpcd)
        system "ln -s /etc/sv/dhcpcd /var/service"
    ;;
esac

[ -n "$desktop" ] && [ "$desktop" != "none" ] &&
    commandFailure="GUI installation has failed"

case "$desktop" in
    gnome)
        install gnome-core gnome-console gnome-tweaks gnome-browser-connector gnome-text-editor xdg-user-dirs xorg-minimal xorg-video-drivers firefox
        system "ln -s /etc/sv/gdm /var/service"
    ;;
    kde)
        install kde-plasma kde-baseapps xdg-user-dirs xorg-minimal xorg-video-drivers firefox
        system "ln -s /etc/sv/sddm /var/service"
    ;;
    xfce)
        install xfce4 xfce4-pulseaudio-plugin lightdm lightdm-gtk3-greeter xorg-minimal xdg-user-dirs xorg-fonts xorg-video-drivers firefox

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        system "ln -s /etc/sv/lightdm /var/service"
    ;;
    i3)
        install i3 i3status xorg-minimal xinit alacritty setxkbmap dmenu dejavu-fonts-ttf xorg-video-drivers xclip xrandr xdg-user-dirs firefox

        [ "$network" == "NetworkManager" ] &&
            install network-manager-applet

        if [ "$lightdm" == "Yes" ]; then
            install lightdm lightdm-gtk3-greeter
            system "ln -s /etc/sv/lightdm /var/service"
        fi
    ;;
esac

[ -n "$audio" ] && [ "$audio" != "none" ] &&
    commandFailure="Audio server installation has failed."

case "$audio" in
    pipewire)
        install pipewire alsa-pipewire wireplumber
        mkdir -p /mnt/etc/alsa/conf.d || die
        mkdir -p /mnt/etc/pipewire/pipewire.conf.d || die

        # This is now required to start pipewire and its session manager 'wireplumber' in an appropriate order, this should achieve a desireable result system-wide.
        echo 'context.exec = [ { path = "/usr/bin/wireplumber" args = "" } ]' > /mnt/etc/pipewire/pipewire.conf.d/10-wireplumber.conf || die
    ;;
    pulseaudio)
        install pulseaudio alsa-plugins-pulseaudio
    ;;
esac

return 0
